# require: rubocop-rspec

inherit_gem:
   rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  DisabledByDefault: true
  Exclude:
    - '**/.DS_Store'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'script/**/*'

  Include:
    - 'app/**/*'
    - 'spec/**/*'
    - 'lib/**/*'
