name: Rspec

on:
  push:
    branches: [ master, 2-0-stable ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master, 2-0-stable ]
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.7, 3.0, 3.1]
    continue-on-error: ${{ endsWith(matrix.ruby-version, 'head') }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Build
        run: |
          sudo apt-get install libsqlite3-dev
          gem install bundler:2.3.8
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rspec
