name: Rspec

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 3.0.2
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.2
      - name: Build
        run: |
          sudo apt-get install libsqlite3-dev
          gem install bundler:2.2.30
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rspec
